# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26d8c0173f331d2bd7c869917ba5dd8d80b17e13af62250116d85b25b25c53cc92f5cba17331210d098eb3c342f890bee6da7b6cb40c58090d451eb87f099c0b

test:
  secret_key_base: eeeb23ad5c00dba00abe077fbd6d239718c99a62eea8e6128bde75fef8daca93aa1c0d31e8ddd140d5594a8ba9a0779e2871dc445258cd009f9ea643da0d4546

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
